test_get_nb_char (__main__.TestExercice) ... FAIL
test_get_nb_words (__main__.TestExercice) ... ERROR
test_pair (__main__.TestExercice) ... ok
test_remove_third_char (__main__.TestExercice) ... ok
test_replace_char (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_get_nb_words (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 75, in test_get_nb_words
    output = [exercice.get_nb_words(v[0], v[1]) for v in values]
  File "test_exercice.py", line 75, in <listcomp>
    output = [exercice.get_nb_words(v[0], v[1]) for v in values]
TypeError: get_nb_words() takes 1 positional argument but 2 were given

======================================================================
ERROR: test_replace_char (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 43, in test_replace_char
    output = [exercice.replace_char(v[0], v[1], v[2]) for v in values]
  File "test_exercice.py", line 43, in <listcomp>
    output = [exercice.replace_char(v[0], v[1], v[2]) for v in values]
  File "/home/runner/work/c03_ch4_exercices-theolouesdon/c03_ch4_exercices-theolouesdon/exercice.py", line 13, in replace_char
    old_char_index = strin.find(old_char)
NameError: name 'strin' is not defined

======================================================================
FAIL: test_get_nb_char (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 65, in test_get_nb_char
    "Mauvais calcul du nombre d'occurences du caractère"
AssertionError: Lists differ: [0, 0, 0] != [4, 1, 0]

First differing element 0:
0
4

- [0, 0, 0]
?  ^  ^

+ [4, 1, 0]
?  ^  ^
 : Mauvais calcul du nombre d'occurences du caractère

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=1, errors=2)
